spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.50.253:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Uyp4Mi4kM#M
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

logging:
  path: /var/logs #配置日志生成路径

dmd:
  uploadfile:
    extension: txt,gif,jpg,png,zip,rar,jpeg,mp4 #使用逗号隔开的字符串，精确匹配例如：txt,jpg,png,zip
    prefix: http://47.107.50.253/project/tomcat/uploadImages
    attachmentPath: /project/tomcat/uploadImages #要保存文件的父路径 D:\
  swagger:
    enable: true